# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Armando Angrisani
tagline:          'PHD Student and Teaching Assistant'
description:      'LIP6, QICS, Sorbonne University'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Armando Angrisani'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
